services:
  frontend:
    container_name: frontend
    build: ./tg_bot
    environment:
      - MAINAPI_URL=http://mainapi:5000
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}    
      - MY_ID=${MY_ID}
    networks:
      - my-network
  
  # mainapi:
  #   container_name: mainapi
  #   build: ./mainapi
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - my-network

networks:
  my-network:
    driver: bridge
